export type Film = {
  id: number,
  previewImage: string,
  posterImage?: string,
  backgroundImage?: string,
  name: string,
  genre?: string,
  released?: number,
  rating?: number,
  scoresCount?: number,
  description?: string,
  director?: string,
  starring?: string[],
  isFavorite?: boolean,
  videoLink?: string,
}
